; Class CSE 313 : Machine Organization 
; Term :: Fall 2018 
; Name(s): Hector Diaz
; Lab 7:

	;f = k+(13m−1)/5+D+D/4+C/4−2C
	;k = day, m = month, D = Last 2 digits of year, C = century 
	; finally do f%7 and remainder gives you day
	; R0 = M, R1 = K, R2 = Y -> C R3 = D, 
	
.ORIG x3000

	LDI R0, M ;LOAD THE MONTH INTO R0 
	LDI R1, K ; LOAD THE DAY INTO R1
	LDI R2, Y ; LOAD THE YEAR INTO R2 
	ST R0, SAVEORIGM ; SAVE THE ORIGINAL MONTH
	ST R1, SAVEORIGK ; SAVE THE ORIGINAL DAY
	ST R2, SAVEORIGY ; SAVE THE ORIGINAL MONTH
	
	JSR CALCM ;JUMP TO CALCULATE THE MONTH NUMBER
	JSR CALCC ;JUMP TO CALCULATE THE CENTURY
	STI R0, M
	
	;JSR CALCY ;CALCULATE THE YEAR
	
	;JSR CALCULATED

	;MULT AND DIV ARE CALLED A NUMBER OF TIMES

	;PUTS ;DISPLAY THE DAY OF THE WEEK ON SCREEN
	HALT

CALCM AND R3, R3, #0 ;CLEAR R3
	ADD R3, R3, R0 ;LOAD THE MONTH INTO R3
	ADD R3, R3, #-2 ;SUBTRACT 2 FROM R3 
	BRnz JANFEB ;IF NEGATIVE OR ZERO GO TO LOOP JANFEB
	BRp OTHERMONTH ;IF ANY OTHER MONTH GO TO LOOP 
	RET 
	
JANFEB ADD R3, R3, #2 ;RETURN TO THE ORIGINAL NUMBER
	AND R0, R0, #0 ;CLEAR R0 TO PUT THE NEW NUMBER 
	ADD R0, R3, #10 ;ADD R3 + 10 TO R0 


OTHERMONTH AND R0, R0, #0 ;CLEAR R0 
	ADD R0, R3, R3 ;ADD R3 TO R0 

	
CALCC AND R4, R4, #0 ;CLEAR R4 
	AND R5, R5, #0 ;CLEAR R5 THIS WILL BE THE TEMP CENT COUNTER
	ADD R4, R4, R2 ;LOAD R2 INTO R4
LOOP ADD R5, R5, #1 ;ADD 1 TO THE TEMP CENTURY COUNTER
	ADD R4, R4, #-15 ; SUBTRACT 100 UNTIL IT REACHES 0 OR NEG
	ADD R4, R4, #-15
	ADD R4, R4, #-15
	ADD R4, R4, #-15
	ADD R4, R4, #-15
	ADD R4, R4, #-15
	ADD R4, R4, #-10
	BRp LOOP 
	BRn CENTURYDONENEG
	BRz CENTURYDONEZERO
	RET 
CENTURYDONENEG ADD R5, R5, #-1
CENTURYDONEZERO ADD R5, R5, #-1

DAYS .STRINGZ "Sunday"
	 .STRINGZ "Monday"
	 .STRINGZ "Tuesday"
	 .STRINGZ "Wednesday"
	 .STRINGZ "Thursday"
	 .STRINGZ "Friday"
	 .STRINGZ "Saturday"
	 
M	.FILL x31F0
K	.FILL x31F1
Y	.FILL x31F2
SAVEORIGM .FILL x0
SAVEORIGK .FILL x0
SAVEORIGY .FILL x0 

.END
