.ORIG x3000
	LDI R0, M ;LOAD THE MONTH INTO R0 
	LDI R1, K ;LOAD THE DAY INTO R1
	LDI R2, CENT ; LOAD THE YEAR INTO R2
	ST R0, SAVEORIGM ; SAVE THE ORIGINAL MONTH
	ST R1, SAVEORIGK ; SAVE THE ORIGINAL DAY
	ST R2, SAVEORIGY ; SAVE THE ORIGINAL YEAR 
	
	JSR CALCM ;JUMP TO CALCULATE THE MONTH NUMBER
	STI R3, M ;STORE THE NEW VALUE INTO 'M'
	ST R3, SAVENEWM ;SAVE THE NEW M
	
			  ;R1 IS THE DATE, NOTHING NEEDS TO BE DONE
	
	JSR CALCC ;JUMP TO CALCULATE THE CENTURY 
	STI R4, CENT ;STORE THE NEW VALUE IN 'CENT'
	ST R4, SAVENEWCENT ;SAVE THE NEW CENTURY
	
	
	JSR CALCY ;JUMP TO CALCULATE THE YEAR  
	STI R4, Y ;STORE THE NEW VALUE IN Y
	ST R4, SAVENEWY ;SAVE THE NEW Y
	
	;AT THIS POINT R0 = MODIFIED MONTH, R1 = DAY, R2 = CENT, R3 = YEAR
	; R1 (DAY) IS THE ONLY REGISTER TO NOT HAVE SOMETHING DONE TO IT
	; IT WILL SERVER AS THE TEMP SUM
	JSR CALCULATE
	
	HALT

CALCM AND R3, R3, #0 ;CLEAR R3
	ADD R3, R3, R0 ;LOAD THE MONTH INTO R3
	ADD R3, R3, #-2 ;SUBTRACT 2 FROM R3 
	BRnz JANFEB ;IF NEGATIVE OR ZERO GO TO LOOP JANFEB
	BRp OTHERMONTH ;IF ANY OTHER MONTH GO TO LOOP 
	RET 	

JANFEB ADD R3, R3, #2 ;RETURN TO THE ORIGINAL NUMBER 
	ADD R3, R3, #10 ;ADD R3 + 10 TO R0 
	RET

OTHERMONTH RET

CALCC AND R3, R3, #0 ; CLEAR R3, WILL HOLD YEAR
	AND R4, R4, #0 ; CLEAR R4, WILL HOLD CENTURY
	ADD R3, R3, R2 ; LOAD THE YEAR INTO R3 
LOOP ADD R4, R4, #1 ;ADD 1 TO THE TEMP CENTURY COUNTER
	ADD R3, R3, #-15 ; SUBTRACT 100 UNTIL IT REACHES 0 OR NEG
	ADD R3, R3, #-15
	ADD R3, R3, #-15
	ADD R3, R3, #-15
	ADD R3, R3, #-15
	ADD R3, R3, #-15
	ADD R3, R3, #-10
	BRp LOOP 
	BRn CENTURYDONENEG
	BRz CENTURYDONEZERO
	RET 
CENTURYDONENEG ADD R4, R4, #-1
	RET
CENTURYDONEZERO ADD R4, R4, #-1
	RET 
	
CALCY ADD R3, R3, #0 ;ADD ZERO TO R3
	BRz YISZERO ;IF THE RESULT IS 0 GO TO YISZERO
	BRn YISNEG  ;IF THE RESULT IS NEG TO TO YISNEG
	RET
YISZERO RET
YISNEG AND R4, R4, #0 ;CLEAR R4
	ADD R4, R4, #15 ;SET R4 = 100 
	ADD R4, R4, #15
	ADD R4, R4, #15
	ADD R4, R4, #15
	ADD R4, R4, #15
	ADD R4, R4, #15
	ADD R4, R4, #10
	ADD R4, R4, R3 ;R4 = R4 - R3 (NEGATIVE YEARS)
	RET 
	
CALCULATE LD R5, SAVENEWM ;LOAD THE MODIFIED M TO R5
	AND R6, R6, #0 ;WILL HOLD FINAL ANSWER
	AND R1, R1, #0 ;CLEAR R1, FIRST PART WILL BE
	ADD R1, R1, #13 ; (13m) 
	BRnzp MULT 
	ADD R5, R5, #-1 ;(13M - 1)
	AND R2, R2, #0	;THIS WILL BE THE DIVIDER
	ADD R2, R2, #-5
	BRn DIV 
	RET

MULT AND R2, R2, #0 ;CLEAR R2 TO HOLD TEMP VALUE
	ADD R2, R2, R5 ;LOAD R0 INTO R2
LOOP2 ADD R5, R5, R2 
	ADD R1, R1, #-1 ;SUBTRACT ONE FROM 13 UNTIL 0
	BRp LOOP2 ;REDO LOOP IF STILL POSITIVE
	BRz ISDONE

ISDONE NOT R2, R2 ;TURN R2 NEGATIVE
	ADD R2, R2, #1 ;ADD 1 TO MAKE IT 2'S COMP
	ADD R5, R5, R2 
	
DIV AND R3, R3, #0	;THIS WILL HOLD ANSWER
LOOP3 ADD R3, R3, #1 ; ADD ONE TO COUNTER
	ADD R5, R5, R2 ;ADD THE NEG NUMBER TO R5 -> DIVIDE
	BRp LOOP3
	BRn DIVNEG
	BRz DIVZERO
DIVNEG ADD R3, R3, #0
	AND R5, R5, #0
	ADD R5, R5, R3 ;ADD R3 TO R5 
DIVZERO ADD R3, R3, #0
	AND R5, R5, #0 
	ADD R5, R5, R3

	


M	.FILL x31F0
K	.FILL x31F1
CENT	.FILL x31F2
Y	.FILL x31F3

SAVEORIGM .FILL x0
SAVEORIGK .FILL x0
SAVEORIGY .FILL x0 
SAVENEWM  .FILL x0
SAVENEWCENT .FILL x0
SAVENEWY .FILL x0 


.END