;LATEST TEST 
; CONVERSION OF M/D/Y WORKS 100%

.ORIG x3000
	LDI R0, M ;LOAD THE MONTH INTO R0 
	LDI R1, K ;LOAD THE DAY INTO R1
	LDI R2, CENT ; LOAD THE YEAR INTO R2
	
	ST R1, SAVEK ;SAVE THE DATE

	JSR CALCM ;JUMP TO CALCULATE THE MONTH NUMBER
	STI R3, M ;STORE THE NEW VALUE INTO 'M'
	ST R3, SAVENEWM ;SAVE THE NEW M
	
			  ;R1 IS THE DATE, NOTHING NEEDS TO BE DONE
	
	JSR CALCC ;JUMP TO CALCULATE THE CENTURY 
	STI R4, CENT ;STORE THE NEW VALUE IN 'CENT'
	ST R4, SAVENEWCENT ;SAVE THE NEW CENTURY
	
	
	JSR CALCY ;JUMP TO CALCULATE THE YEAR  
	STI R4, Y ;STORE THE NEW VALUE IN Y
	ST R4, SAVENEWY ;SAVE THE NEW Y
	
PART1 JSR MULTPT1 ;[(13m - 1)]
	ADD R5, R5, #-1
	JSR DIVPT1 ;(13m-1)[/5]

PART2 ADD R5, R5, R1 ;[K]+(13m -1)/5

PART3 LD R4, SAVENEWY ;K+(13m-1)/5+[D]
	ADD R5, R5, R4
	ST R5, SAVENEWM ;STORE IN SAVENEWM

PART4 AND R5, R5, #0 ;CLEAR R5 FOR NEXT STEP
	JSR DIVPT2	;K+(13m-1)/5+D+[D/4]
	AND R4, R4, #0 ;CLEAR R4 TO ADD # SO FAR
	LD R4, SAVENEWM ;LOAD # SO FAR
	ADD R5, R5, R4 ;ADD # SO FAR TO DIV PT2
	ST R5, SAVENEWM ; STORE IT IN SAVENEWM AGAIN

PART5 AND R5, R5, #0 ;CLEAR R5
	JSR DIVPT3 ;K+(13m-1)/5+D+D/4+[C/4]
	AND R4, R4, #0
	LD R4, SAVENEWM
	ADD R5, R5, R4
	ST R5, SAVENEWM

PART6 AND R5, R5, #0 ;K+(13m-1)/5+D+D/4+C/4[-2C]
	JSR MULTPT2
	NOT R5, R5 ;CONVERT TO 2'S COMP SINCE
	ADD R5, R5, #1 ; IT IS (-2C)
	AND R4, R4, #0
	LD R4, SAVENEWM
	ADD R5, R5, R4
	ST R5, SAVENEWM

PART7 AND R5, R5, #0
	JSR FINALMOD
	
	AND R3, R3, #0
	ADD R3, R3, R5
	AND R0, R0, #0
	LEA R0, DAYS
DISLOOP		ADD R3, R3, #0
		BRz DISPLAY
		ADD R0, R0, #10
		ADD R3, R3, #-1
		BR DISLOOP
DISPLAY 	PUTS	
	
HALT


CALCM AND R3, R3, #0 ;CLEAR R3
	ADD R3, R3, R0 ;LOAD THE MONTH INTO R3
	ADD R3, R3, #-2 ;SUBTRACT 2 FROM R3 
	BRnz JANFEB ;IF NEGATIVE OR ZERO GO TO LOOP JANFEB
	BRp OTHERMONTH ;IF ANY OTHER MONTH GO TO LOOP 
	RET 	

JANFEB ADD R3, R3, #2 ;RETURN TO THE ORIGINAL NUMBER 
	ADD R3, R3, #10 ;ADD R3 + 10 TO R0 
	RET

OTHERMONTH RET

CALCC AND R3, R3, #0 ; CLEAR R3, WILL HOLD YEAR
	AND R4, R4, #0 ; CLEAR R4, WILL HOLD CENTURY
	ADD R3, R3, R2 ; LOAD THE YEAR INTO R3 
LOOP ADD R4, R4, #1 ;ADD 1 TO THE TEMP CENTURY COUNTER
	ADD R3, R3, #-15 ; SUBTRACT 100 UNTIL IT REACHES 0 OR NEG
	ADD R3, R3, #-15
	ADD R3, R3, #-15
	ADD R3, R3, #-15
	ADD R3, R3, #-15
	ADD R3, R3, #-15
	ADD R3, R3, #-10
	BRp LOOP 
	BRn CENTURYDONENEG
	BRz CENTURYDONEZERO
	RET 
CENTURYDONENEG ADD R4, R4, #-1
	RET
CENTURYDONEZERO ADD R4, R4, #-1
	RET 
	
CALCY ADD R3, R3, #0 ;ADD ZERO TO R3
	BRz YISZERO ;IF THE RESULT IS 0 GO TO YISZERO
	BRn YISNEG  ;IF THE RESULT IS NEG TO TO YISNEG
	RET
YISZERO RET
YISNEG AND R4, R4, #0 ;CLEAR R4
	ADD R4, R4, #15 ;SET R4 = 100 
	ADD R4, R4, #15
	ADD R4, R4, #15
	ADD R4, R4, #15
	ADD R4, R4, #15
	ADD R4, R4, #15
	ADD R4, R4, #10
	ADD R4, R4, R3 ;R4 = R4 - R3 (NEGATIVE YEARS)
	RET 
	
MULTPT1 LD R5, SAVENEWM ;LOAD THE NEW M TO R5 
	AND R0, R0, #0 ;CLEAR R0
	ADD R0, R0, #13 ; ADD 13 TO IT
	BRp MULT
	RET

MULTPT2 LD R5, SAVENEWCENT ;LOAD CENT INTO R5
	AND R0, R0, #0 ;CLEAR R0
	ADD R0, R0, #2 ; ADD 2 TO IT
	BRp MULT
	RET
	
MULT AND R2, R2, #0 ; CLEAR R2
	ADD R2, R2, R5 ; LOAD R5 INTO R2
LOOP2 ADD R5, R5, R2 ; ADD X + X
	ADD R0, R0 #-1 ;TAKE AWAY ONE FROM COUNTER
	BRp LOOP2
	BRz ISDONE
ISDONE NOT R2, R2 ;AFTER GOING 1x OVER, NEED TO SUBTRACT X
	ADD R2, R2, #1
	ADD R5, R5, R2
	RET

DIVPT1 AND R0, R0, #0 ;WILL HOLD THE 5 NEEDED TO DIVIDE
	AND R3, R3, #0 ;WILL BE THE COUNTER
	ADD R0, R0, #5 ;ADD 5 TO DIVIDE WITH
	BRp DIV
	RET

DIVPT2 LD R5, SAVENEWY ;LOAD THE YEAR INTO R5
	AND R3, R3, #0
	AND R0, R0 #0
	ADD R0, R0, #4 ;WILL DIVIDE BY 4 (D/4)
	BRp DIV 
	RET
	
DIVPT3 LD R5, SAVENEWCENT
	AND R3, R3, #0
	AND R0, R0, #0
	ADD R0, R0, #4
	BRp DIV
	RET
	
;R5 = # TO BE DIV, R0 = DIVIDING #, R3 = COUNTER
DIV NOT R0, R0 ;WILL CONVERT R0 TO 2'S COMP
	ADD R0, R0, #1 ;TO DO SUBTRACTION
LOOP3 ADD R3, R3, #1
	ADD R5, R5, R0 ; ADD NEG # TO R5 TO DIV 
	BRp LOOP3
	BRz DIVZERO
	BRn	DIVNEG
DIVZERO AND R5, R5, #0
	ADD R5, R5, R3
RET
DIVNEG AND R5, R5, #0
	ADD R3, R3, #-1
	ADD R5, R5, R3
	RET

FINALMOD LD R5, SAVENEWM ;LOAD NUMBER SO FAR IN R5
	AND R0, R0, #0 ;WILL DO MOD 7
	ADD R0, R0, #7
	BRp MODS

MODS NOT R0, R0 ;WILL CONVERT R0 TO 2'S COMP
	ADD R0, R0, #1 ;TO DO SUBTRACTION
LOOP4 ADD R5, R5, R0 ; ADD NEG # TO R5 TO DIV 
	BRp LOOP4
	BRz DIVRESZERO
	BRn	DIVRESNEG
	RET
DIVRESZERO RET
DIVRESNEG ADD R5, R5, #7
	RET
	
	
M	.FILL x31F0
K	.FILL x31F1
CENT	.FILL x31F2
Y	.FILL x31F3
TMP .FILL x31F4

SAVENEWM  .FILL x0
SAVENEWCENT .FILL x0
SAVENEWY .FILL x0
SAVEK .FILL x0 
DAYS		.STRINGZ "Sunday   "
		.STRINGZ "Monday   "
		.STRINGZ "Tuesday  "
		.STRINGZ "Wednesday"
		.STRINGZ "Thursday "
		.STRINGZ "Friday   "
		.STRINGZ "Saturday "
.END